import {currentLanguage,setLanguage,t} from './i18n.js';
import {createMercuryOrb} from './mercury-orb.js';
const tauri=window.__TAURI__||{core:{invoke:async c=>c==='load_settings'?{}:c==='connection_state'?{state:'disconnected',elapsed:0}:c==='installed_applications'?[]:c==='traffic_totals'?{uploaded:0,downloaded:0}:c==='vpn_probe'?{ping:null,location:''}:undefined},event:{listen:async()=>()=>{}},opener:{openUrl:async()=>{}},dialog:{open:async()=>null}};
const {invoke}=tauri.core,{listen}=tauri.event,openUrl=tauri.opener?.openUrl||tauri.opener?.open,$=id=>document.getElementById(id);
const defaults={automaticUpdates:true,language:'en',appearance:'system',orbStyle:'living-mercury',connectionMode:'vpn',routingMode:'bypass-local',dnsLeakProtection:true,ipv6Behavior:'tunnel',killSwitch:false,splitApplications:[],routeExclusions:[],protocol:'gool',scanMode:'balanced',logLevel:'info',ipMode:'v4',obfuscation:'balanced',masqueTransport:'h3',socksAddress:'127.0.0.1:1819',allowRemoteListener:false,peer:'',wgKeepalive:5,stallTimeout:90,watchdog:true,configPath:'',wgConfigPath:'',masqueConfigPath:'',quickReconnect:true,autoConnectAtStart:false};
let settings={...defaults},state='disconnected',trafficTimer,pingTimer,locationTimer,reconnectTimer,reconnectAttempts=0,desiredConnected=false,operation=null,operationVersion=0,probeInFlight=false,pingInFlight=false,locationInFlight=false,telemetryGeneration=0,apps=[],selected=new Set(),connectStartedAtMs=0,connectedTimelineRecorded=false,connectAttemptSequence=0,activeAttemptId='',initialized=false,pendingConnect=false;
let mercuryOrb;
function frontendPhase(stage,result='success',errorCategory='',error=''){const timestampMs=Date.now(),monotonicMs=Math.round(performance.timeOrigin+performance.now());console.info('[timeline-ui]',JSON.stringify({timelineId:activeAttemptId,attemptId:activeAttemptId,sessionGeneration:operationVersion,protocol:settings.protocol,connectionMode:settings.connectionMode,stage,timestampMs,monotonicMs,elapsedMs:connectStartedAtMs?timestampMs-connectStartedAtMs:0,result,errorCategory,error:error?String(error?.message||error):''}))}
function selectSegment(id,value){$(id)?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.value===value))}
function segmentValue(id){return $(id)?.querySelector('.active')?.dataset.value}
function setOptions(el,values,selectedValue){el.replaceChildren(...values.map(([value,label])=>{const o=document.createElement('option');o.value=value;o.textContent=label;o.selected=value===selectedValue;return o}))}
function formatNumber(value){return new Intl.NumberFormat(currentLanguage(),{minimumFractionDigits:1,maximumFractionDigits:1}).format(value)}
function formatBytes(value){if(!Number.isFinite(value)||value<0)return'--';if(value<1048576)return formatNumber(value/1024)+' KB';if(value<1073741824)return formatNumber(value/1048576)+' MB';return formatNumber(value/1073741824)+' GB'}
function formatLocation(value){const location=(value||'').trim();if(!/^[A-Z]{2}$/.test(location))return location;try{return new Intl.DisplayNames([currentLanguage()],{type:'region'}).of(location)||location}catch{return location}}
function renderOptions(){setOptions($('scanMode'),[['turbo','Turbo'],['balanced','Balanced'],['thorough','Thorough'],['stealth','Stealth'],['ironclad','Ironclad']],settings.scanMode);setOptions($('obfuscation'),[['firewall','Firewall'],['gfw','GFW'],['balanced','Balanced'],['aggressive','Aggressive'],['off','Off']],settings.obfuscation);syncProtocol()}
function syncProtocol(){settings.protocol=segmentValue('protocol')||settings.protocol;$('transportField').classList.toggle('hidden',settings.protocol!=='masque')}
function updateSelectedCount(){$('selectedCount').textContent=new Intl.NumberFormat(currentLanguage()).format(selected.size)+' '+t('picker.selected')}
function syncSplit(){const on=$('splitEnabled').checked;$('splitControls').classList.toggle('hidden',!on);settings.routingMode=on?(segmentValue('splitMode')||'split-include'):'bypass-local';updateSelectedCount()}
function readSettings(){return{...settings,language:currentLanguage(),appearance:$('appearance').value,orbStyle:$('orbStyle').value,automaticUpdates:$('automaticUpdates').checked,autoConnectAtStart:$('autoConnectAtStart').checked,connectionMode:segmentValue('connectionMode'),routingMode:settings.routingMode,protocol:segmentValue('protocol'),masqueTransport:segmentValue('transport')||settings.masqueTransport,scanMode:$('scanMode').value,obfuscation:$('obfuscation').value,dnsLeakProtection:$('dnsLeakProtection').checked,killSwitch:$('killSwitch').checked,quickReconnect:$('quickReconnect').checked,allowRemoteListener:$('allowRemoteListener').checked,peer:$('peer').value.trim(),splitApplications:[...selected]}}
function queueSave(){settings=readSettings();clearTimeout(queueSave.timer);queueSave.timer=setTimeout(()=>invoke('save_settings',{settings}).catch(showError),250)}
async function refreshLanStatus(){try{const lan=await invoke('lan_status',{settings:readSettings()});$('lanAddressValue').textContent=lan.enabled&&lan.address?`${lan.address}:${lan.port}`:'LAN sharing disabled'}catch{$('lanAddressValue').textContent='LAN status unavailable'}}
function applyOrbStyle(){const selected=$('orbStyle')?.value==='living-mercury'?'living-mercury':'classic';if(mercuryOrb){mercuryOrb.setStyle(selected);mercuryOrb.setState(state);mercuryOrb.setTheme(settings.appearance)}$('connectionOrb')?.classList.toggle('living-mercury',selected==='living-mercury');$('mercuryVisual')?.classList.toggle('active',selected==='living-mercury')}
function renderSettings(saved){settings={...defaults,...saved};setLanguage(settings.language);selectSegment('connectionMode',settings.connectionMode);selectSegment('protocol',settings.protocol);selectSegment('transport',settings.masqueTransport);selectSegment('splitMode',settings.routingMode==='split-exclude'?'split-exclude':'split-include');selected=new Set(settings.splitApplications||[]);$('splitEnabled').checked=['split-include','split-exclude'].includes(settings.routingMode);$('peer').value=settings.peer||'';$('dnsLeakProtection').checked=settings.dnsLeakProtection;$('killSwitch').checked=settings.killSwitch;$('quickReconnect').checked=settings.quickReconnect;$('autoConnectAtStart').checked=settings.autoConnectAtStart;$('allowRemoteListener').checked=settings.allowRemoteListener;$('automaticUpdates').checked=settings.automaticUpdates;$('appearance').value=settings.appearance;$('orbStyle').value=settings.orbStyle;$('language').value=settings.language;document.body.dataset.theme=settings.appearance;renderOptions();syncSplit();$('currentVersion').textContent='2.4.2';applyOrbStyle();refreshLanStatus()}
function openDrawer(){$('drawer').classList.add('open');$('drawerScrim').classList.add('open')}
function closeDrawer(){$('drawer').classList.remove('open');$('drawerScrim').classList.remove('open')}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$('pageTitle').textContent=name==='connect'?'Aethon VPN':t('nav.'+name);closeDrawer();window.scrollTo({top:0,behavior:'instant'});if(name==='diagnostics')refreshDiagnostics()}
function setState(next){state=next;mercuryOrb?.setState(next);const active=!['disconnected','error'].includes(next);$('connectionOrb').className='connection-orb '+next+($('orbStyle')?.value==='living-mercury'?' living-mercury':'');$('statusPill').className='status-pill '+next;$('orbLabel').textContent=next==='connected'?t('actions.disconnect'):next==='disconnecting'?t('status.disconnecting'):active?t('status.connecting'):t('actions.connect');$('statusTitle').textContent=t('status.'+next);const key=next==='connected'?'connected':next==='reconnecting'?'reconnecting':next==='disconnecting'?'disconnecting':next==='disconnected'?'ready':next==='scanning'||next==='connecting'?'connecting':'error';$('statusMessage')?.replaceChildren(document.createTextNode(t('connection.'+key)));$('drawerState').textContent=t('status.'+next);if(next==='connected'&&!connectedTimelineRecorded&&connectStartedAtMs){connectedTimelineRecorded=true;frontendPhase('t20_ui_connected');startTelemetry()}if(next==='disconnected'||next==='error'){stopTelemetry();$('uploadTraffic').textContent='--';$('downloadTraffic').textContent='--';$('pingValue').textContent='--';$('locationValue').textContent='\u2014'}else if(next==='reconnecting'){stopTelemetry();$('pingValue').textContent='--';$('locationValue').textContent=t('traffic.locationDetecting')}else if(next!=='connected'){$('pingValue').textContent='--';$('locationValue').textContent=t('traffic.locationDetecting')}}
function showError(error){$('toast').textContent=typeof error==='string'?error:error?.message||String(error);$('toast').className='show error';setTimeout(()=>$('toast').className='',5000)}
function toast(message){$('toast').textContent=message;$('toast').className='show';setTimeout(()=>$('toast').className='',2600)}
async function connect(){if(!initialized){pendingConnect=true;return}if(operation||!['disconnected','error'].includes(state))return;connectStartedAtMs=Date.now();connectedTimelineRecorded=false;const clientStartedAtMs=connectStartedAtMs,version=++operationVersion;activeAttemptId=`ui-${clientStartedAtMs}-${++connectAttemptSequence}`;let retryAfterFailure=false;operation='connect';desiredConnected=true;settings=readSettings();frontendPhase('frontend_connect_start');setState('connecting');frontendPhase('backend_connect_ipc_start');const backendConnect=invoke('connect',{settings,clientStartedAtMs,attemptId:activeAttemptId});frontendPhase('settings_save_start');const settingsSave=invoke('save_settings',{settings}).then(()=>frontendPhase('settings_save_success')).catch(error=>{frontendPhase('settings_save_failure','failure','settings_persistence',error);console.warn('[settings-save]',error)});setState('scanning');try{await backendConnect;frontendPhase('backend_connect_ipc_success');if(version===operationVersion){reconnectAttempts=0;const snapshot=await invoke('connection_state');if(snapshot.state==='disconnected'){desiredConnected=false;setState('disconnected')}}}catch(error){frontendPhase('backend_connect_ipc_failure','failure','backend_connect',error);if(version===operationVersion){setState('error');showError(error);retryAfterFailure=desiredConnected&&settings.quickReconnect}}finally{void settingsSave;if(version===operationVersion){operation=null;if(retryAfterFailure)scheduleReconnect()}}}
async function disconnect(){if(operation==='disconnect'||state==='disconnecting'||state==='disconnected')return;const version=++operationVersion;operation='disconnect';desiredConnected=false;clearTimeout(reconnectTimer);reconnectTimer=null;frontendPhase('disconnect_clicked');stopTelemetry();setState('disconnecting');frontendPhase('disconnecting_visible');try{await invoke('disconnect')}catch(error){if(version===operationVersion)showError(error)}finally{if(version===operationVersion){frontendPhase('disconnect_complete');operation=null;setState('disconnected')}}}
function scheduleReconnect(){if(!desiredConnected||!settings.quickReconnect||reconnectAttempts>=5||reconnectTimer||operation)return false;reconnectAttempts++;setState('reconnecting');reconnectTimer=setTimeout(async()=>{reconnectTimer=null;if(!desiredConnected||operation)return;const version=++operationVersion;operation='disconnect';try{await invoke('disconnect')}finally{if(version===operationVersion){operation=null;if(desiredConnected){setState('disconnected');connect()}}}},Math.min(20000,1500*2**(reconnectAttempts-1)));return true}
function stopTelemetry(){telemetryGeneration++;clearInterval(trafficTimer);clearInterval(pingTimer);clearInterval(locationTimer);trafficTimer=pingTimer=locationTimer=null;probeInFlight=false;pingInFlight=false;locationInFlight=false}
function startTelemetry(){stopTelemetry();const generation=telemetryGeneration,traffic=async()=>{try{const m=await invoke('traffic_totals');if(generation!==telemetryGeneration||state!=='connected')return;$('uploadTraffic').textContent=formatBytes(m.uploaded);$('downloadTraffic').textContent=formatBytes(m.downloaded)}catch{}};const ping=async()=>{if(probeInFlight||pingInFlight||generation!==telemetryGeneration||state!=='connected')return;probeInFlight=pingInFlight=true;frontendPhase('ping_probe_started');try{const value=await invoke('vpn_ping',{settings});if(generation!==telemetryGeneration||state!=='connected')return;if(value!=null){$('pingValue').textContent=new Intl.NumberFormat(currentLanguage()).format(value)+' ms';frontendPhase('ping_available')}}catch(error){if(generation===telemetryGeneration&&state==='connected')$('pingValue').textContent='--';console.info('[ping]',error)}finally{probeInFlight=pingInFlight=false}};const location=async()=>{if(locationInFlight||generation!==telemetryGeneration||state!=='connected')return;locationInFlight=true;frontendPhase('location_probe_started');try{const value=await invoke('vpn_location',{settings});if(generation!==telemetryGeneration||state!=='connected')return;$('locationValue').textContent=formatLocation(value)||t('traffic.locationUnavailable');frontendPhase('location_available')}catch(error){if(generation===telemetryGeneration&&state==='connected')$('locationValue').textContent=t('traffic.locationUnavailable');console.info('[location]',error)}finally{locationInFlight=false}};traffic();void ping();void location();trafficTimer=setInterval(traffic,1000);pingTimer=setInterval(ping,15000);locationTimer=setInterval(location,30000)}
async function openTelegram(){try{await openUrl('tg://resolve?domain=hamvex')}catch{try{await openUrl('https://t.me/hamvex')}catch{toast(t('toast.telegram'))}}}
async function checkUpdates(manual=false){$('checkUpdates').disabled=true;if(manual)$('updateStatus').textContent=t('updates.checking');try{const info=await invoke('check_for_update');$('currentVersion').textContent=info.currentVersion||'2.1.1';$('updateBadge').classList.toggle('hidden',!info.available);if(info.available){$('updateStatus').textContent=t('updates.available');$('updateAction').classList.remove('hidden');$('updateAction').textContent=t('updates.download')}else if(manual){$('updateStatus').textContent=t('updates.upToDate');toast(t('toast.updated'))}}catch(error){if(manual){$('updateStatus').textContent=t('updates.failed');showError(error)}}finally{$('checkUpdates').disabled=false}}
async function updateAction(){try{if($('updateAction').textContent===t('updates.install')){await invoke('install_update');return}$('updateProgress').classList.remove('hidden');await invoke('download_update');$('updateAction').textContent=t('updates.install');$('updateStatus').textContent=t('updates.ready')}catch(error){showError(error)}}
async function refreshDiagnostics(){try{const d=await invoke('network_diagnostics',{settings:readSettings()});$('diagProtocol').textContent=d.protocol||'--';$('diagTun').textContent=d.tunInterface||'--';$('diagMtu').textContent=d.runtimeMtu||'--';$('diagExitIp').textContent=d.exitIp||'--';$('diagPing').textContent=d.pingMs==null?'--':d.pingMs+' ms';$('diagTraffic').textContent='↓ '+formatBytes(d.downloadBytes)+' / ↑ '+formatBytes(d.uploadBytes);$('diagState').textContent=d.tunnelState||'--';$('diagAetherVersion').textContent=d.aetherVersion||'--';$('diagProcesses').textContent=(d.aetherRunning?'running':'stopped')+' / '+(d.xrayRunning?'running':'stopped')}catch(error){showError(error)}}
function renderApps(){const query=$('appSearch').value.toLowerCase(),visible=apps.filter(a=>(a.name+' '+a.path).toLowerCase().includes(query));$('appList').replaceChildren(...visible.map(app=>{const row=document.createElement('div');row.className='app-row';row.innerHTML='<span class="app-icon">EXE</span><span><b></b><small></small></span><input type="checkbox">';if(app.icon){const image=document.createElement('img');image.className='app-icon';image.alt='';image.src='data:image/png;base64,'+app.icon;row.querySelector('.app-icon').replaceWith(image)}row.querySelector('b').textContent=app.name;row.querySelector('small').textContent=app.path;row.querySelector('input').checked=selected.has(app.path);row.onclick=e=>{if(e.target.tagName!=='INPUT')row.querySelector('input').checked=!row.querySelector('input').checked;row.querySelector('input').checked?selected.add(app.path):selected.delete(app.path);updateSelectedCount()};return row}))}
async function openApps(){try{apps=await invoke('installed_applications');for(const path of selected)if(!apps.some(a=>a.path===path))apps.push({name:path.split(/[\\/]/).pop(),path,icon:''});renderApps();$('appDialog').classList.remove('hidden')}catch(error){showError(error)}}
function closeApps(){$('appDialog').classList.add('hidden')}
mercuryOrb=createMercuryOrb($('mercuryCanvas'),{onFallback:reason=>{settings.orbStyle='classic';if($('orbStyle'))$('orbStyle').value='classic';$('connectionOrb')?.classList.remove('living-mercury');$('mercuryVisual')?.classList.remove('active');console.info('[mercury-orb] classic fallback',reason)}});
renderSettings(defaults);
$('menuButton').onclick=openDrawer;$('drawerScrim').onclick=closeDrawer;$('telegramButton').onclick=openTelegram;document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('connectionOrb').onclick=()=>state==='disconnecting'?undefined:['connected','scanning','connecting','reconnecting'].includes(state)?disconnect():connect();
$('connectionMode').onclick=e=>{if(e.target.dataset.value){selectSegment('connectionMode',e.target.dataset.value);syncProtocol();queueSave()}};$('protocol').onclick=e=>{if(e.target.dataset.value){selectSegment('protocol',e.target.dataset.value);syncProtocol();queueSave()}};$('transport').onclick=e=>{if(e.target.dataset.value){selectSegment('transport',e.target.dataset.value);queueSave()}};$('splitMode').onclick=e=>{if(e.target.dataset.value){selectSegment('splitMode',e.target.dataset.value);syncSplit();queueSave()}};$('splitEnabled').onchange=()=>{syncSplit();queueSave()};
document.querySelectorAll('input,select').forEach(e=>e.addEventListener('change',()=>{if(e.id==='language'){settings.language=e.value;setLanguage(e.value);setState(state);updateSelectedCount()}if(e.id==='appearance'){document.body.dataset.theme=e.value;mercuryOrb?.setTheme(e.value)}if(e.id==='orbStyle')applyOrbStyle();queueSave()}));$('resetSettings').onclick=()=>{renderSettings(defaults);queueSave()};$('openApps').onclick=openApps;$('closeApps').onclick=closeApps;$('applyApps').onclick=()=>{closeApps();queueSave()};$('appSearch').oninput=renderApps;$('selectAll').onclick=()=>{apps.forEach(a=>selected.add(a.path));renderApps();updateSelectedCount()};$('clearAll').onclick=()=>{selected.clear();renderApps();updateSelectedCount()};
$('manageNotifications').onclick=()=>openUrl('ms-settings:notifications').catch(showError);$('addExecutable').onclick=async()=>{try{const path=await tauri.dialog.open({multiple:false,filters:[{name:'Executable',extensions:['exe']}]});if(path){selected.add(path);if(!apps.some(a=>a.path===path))apps.push({name:path.split(/[\\/]/).pop(),path,icon:''});renderApps();toast(t('picker.added'))}}catch(error){showError(error)}};$('checkUpdates').onclick=()=>checkUpdates(true);$('updateAction').onclick=updateAction;document.querySelectorAll('[data-external]').forEach(b=>b.onclick=()=>openUrl(b.dataset.external).catch(showError));
$('refreshDiagnostics').onclick=refreshDiagnostics;
await listen('aether-log',e=>console.info('[Aether]',e.payload));await listen('aether-status',e=>{if(operation==='disconnect'&&e.payload.state!=='disconnected')return;if(!desiredConnected&&!['disconnected','error'].includes(e.payload.state))return;if(e.payload.state==='error'&&scheduleReconnect())return;setState(e.payload.state);if(e.payload.state==='connected')startTelemetry()});await listen('routing-status',e=>{if(operation==='disconnect'||!desiredConnected)return;if(e.payload.state==='reconnecting')setState('reconnecting');if(e.payload.state==='error'&&!scheduleReconnect())setState('error');if(e.payload.state==='connected'){reconnectAttempts=0;startTelemetry()}});await listen('update-progress',e=>{if(e.payload.percent!=null){$('updateProgress').classList.remove('hidden');$('updateProgress').value=e.payload.percent}});await listen('tray-connect',connect);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('appDialog').classList.contains('hidden'))closeApps();else closeDrawer()}if(e.key==='Backspace'&&!['INPUT','SELECT'].includes(document.activeElement.tagName)&&!$('view-connect').classList.contains('active'))showView('connect')});
try{renderSettings(await invoke('load_settings'))}catch{renderSettings(defaults)}try{const snapshot=await invoke('connection_state');desiredConnected=snapshot.state!=='disconnected';setState(snapshot.state);if(snapshot.state==='connected')startTelemetry()}catch{setState('disconnected')}initialized=true;if(pendingConnect&&state==='disconnected'){pendingConnect=false;setTimeout(()=>connect(),0)}else if(state==='disconnected'&&settings.autoConnectAtStart)setTimeout(()=>connect(),800);if(settings.automaticUpdates)setTimeout(()=>checkUpdates(false),1200);setInterval(()=>{if(settings.automaticUpdates)checkUpdates(false)},12*60*60*1000);
